const CLOCKWISE = 'clockwise';
const ANTICLOCKWISE = 'anticlockwise';

const TIMER_STATUS_RUNNING = 'running';
const TIMER_STATUS_PAUSED = 'paused';
const TIMER_STATUS_STOPED = 'stoped';
const TIMER_STATUS_FINISHED = 'finished';

export {
  CLOCKWISE,
  ANTICLOCKWISE,
  TIMER_STATUS_RUNNING,
  TIMER_STATUS_PAUSED,
  TIMER_STATUS_STOPED,
  TIMER_STATUS_FINISHED
};
